### PR TITLE
implemented redirect on signup

### PR DESCRIPTION
**Pull request by Jyaleen**
### ℹ️ Issue

Closes [[clickup ticket link](https://app.clickup.com/t/2mjpz27)](https://app.clickup.com/)

### 📝 Description

- logout now redirects to "/"
- :^)

### CODE REVIEW

**Review by rymaju — APPROVED** [review]
LGTM
investigating why CI failed 👀

**Review by vrautela — APPROVED** [review]
I mean this looks good to me. I assume you tested it manually

**Review by rymaju — CHANGES_REQUESTED** [review]
Please revert changes to package lock!

**Comment by DerekL27** [comment]
> Please revert changes to package lock!
@rymaju 
my bad

**Review by rymaju — APPROVED** [review]
LGTM

**Comment by onb6** [comment]
I think the name of the PR should be redirect on logout LOL

**Review by onb6 — APPROVED** [review]
👍🎉

**Pull request merged**
